baseURL: https://example.com/
languageCode: en-US
title: Siobhan Oberg
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Chris Turner
  avatar: img/Sioprofile.png
  custom_css: []
  custom_js: []
  description: Describe your website
  social:
    Email: aso35170@gmail.com
    Github: a-siobhan
    LinkedIn: siobhan-oberg
menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 100
    - identifier: resume
      name: resume
      url: /resume/
      weight: 200
